baseURL: https://sris.co
languageCode: en-us
defaultContentLanguage: en
title: sris.co
theme: congo
copyright: "© Sebastián Risco"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-BGSTB91JYZ

minify:
  disableXML: true
  minifyOutput: true

disableKinds:
- taxonomy
- term

params:
  env: production
  keywords: [Portfolio, Sebastián Risco]
  colorScheme: slate
  homepage:
    layout: profile
    showRecent: false
  article:
    showDate: false
    showAuthor: false
    showReadingTime: false
    showPagination: false
  author:
    name: Sebastián Risco
    image: img/profile.jpg
    links:
    - email: mailto:sebas@sris.co
    - github: https://github.com/srisco
    - x-twitter: https://twitter.com/sriscog
    - researchgate: https://www.researchgate.net/profile/Sebastian-Risco
    - linkedin: https://es.linkedin.com/in/sebasrisco
    - orcid: https://orcid.org/0000-0002-7710-2182
  footer:
    showAppearanceSwitcher: true
    showThemeAttribution: false
    showScrollToTop: true

menu:
  main:
  - identifier: about
    name: About
    url: /about/
    weight: 10
  - identifier: publications
    name: Publications
    url: /publications/
    weight: 10



